version: "3"
services:
  app:
    container_name: todoapp
    restart: always
    build: .
    ports:
      - "8208:8208"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"